apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coffee-journal-api.fullname" . }}-config
  namespace: {{ include "coffee-journal-api.namespace" . }}
  labels:
    {{- include "coffee-journal-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  NODE_OPTIONS: {{ .Values.config.nodeOptions | quote }}
  KEYCLOAK_JWKS_URL: {{ .Values.config.keycloakJwksUrl | quote }}
  KEYCLOAK_ISSUER: {{ .Values.config.keycloakIssuer | quote }}
  KEYCLOAK_ADMIN_BASE_URL: {{ .Values.config.keycloakAdminBaseUrl | quote }}
  KEYCLOAK_ADMIN_REALM: {{ .Values.config.keycloakAdminRealm | quote }}
  KEYCLOAK_ADMIN_CLIENT_ID: {{ .Values.config.keycloakAdminClientId | quote }}
  S3_ENDPOINT: {{ .Values.config.s3Endpoint | quote }}
  S3_REGION: {{ .Values.config.s3Region | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  AI_BEAN_EXTRACTION_MODEL: {{ .Values.config.aiBeanExtractionModel | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otlpEndpoint | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ .Values.config.otlpProtocol | quote }}
  OTEL_SERVICE_VERSION: {{ .Values.image.tag | quote }}
  NODE_ENV: {{ .Values.config.deploymentEnvironment | quote }}
