apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coffee-journal-api.fullname" . }}-config
  namespace: {{ include "coffee-journal-api.namespace" . }}
  labels:
    {{- include "coffee-journal-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  KEYCLOAK_JWKS_URL: {{ .Values.config.keycloakJwksUrl | quote }}
  KEYCLOAK_ISSUER: {{ .Values.config.keycloakIssuer | quote }}
  KEYCLOAK_ADMIN_BASE_URL: {{ .Values.config.keycloakAdminBaseUrl | quote }}
  KEYCLOAK_ADMIN_REALM: {{ .Values.config.keycloakAdminRealm | quote }}
  KEYCLOAK_ADMIN_CLIENT_ID: {{ .Values.config.keycloakAdminClientId | quote }}
